### ISSUE TITLE
Issue installing VCMI

### ISSUE THREAD

**Issue by EMiiiiiler** [Exarkuniv/RetroPie-Extra#155]
Hello, 

The work you've done here is incredible! I never thought I'd be able to install VCMI on my retropie and I'm so close to getting it working.
I ran the installer and installed it using the retropie configs, but everytime I try to get VCMI to install a heroes 3 exe it keeps failing.

```
cd /home/pi/RetroPie/roms/ports/vcmi
sudo apt-get install innoextract
./vcmibuilder --gog setup_heroes_of_might_and_magic_3_complete_4.0_28740.exe
Warning: Unexpected setup data version: 5.6.2 (unicode)
Warning: Unexpected Auto Boolean value: 19
Warning: Unexpected Auto Boolean value: 20
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Stream error while parsing setup headers!
 ├─ detected setup version: 5.6.2 (unicode)
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 8 warnings.

```

It's weird that this is the case as that was the .exe file I just downloaded from gog. Any hints?

Cheers for your help.

**Comment by Exarkuniv** [comment]
i never used or tried  ./vcmibuilder 
it was intended to have the files installed on your PC and you just copy the required files from that.

but if you need to run ./vcmibuilder and its not working for you. you need to go and open a issue ticket on https://github.com/vcmi/vcmi since its their software.  but is seems like it does not like the exe file that you have. not sure why

all i do is make a script to install the port
 sorry

**Comment by EMiiiiiler** [comment]
@Exarkuniv copying across the data from my computer and running it with the data option worked successfully!
I can't seem to run it via EmulationStation, is there any additional steps I need to do there?

**Comment by Exarkuniv** [comment]
All you need to do is Copy Data, Maps and Mp3 from Heroes III to roms/ports/vcmi from the hero 3 game that you install on your computer 

There should be a "Heroes of Might and Magic III" .sh in the ports selection in EmulationStation. 

You just select it like any other game.

There is no need for to use ./vcmibuilder. That will not start the game

**Comment by EMiiiiiler** [comment]
Epic, it didn't work on mine, but it could've been because I'd been moving a few files around the roms/ports/vcmi area, so I'm uninstalling the package, reinstalling and moving the maps, data + mp3 across and I'll report back and see if that works.

Cheers for all your help

**Comment by Exarkuniv** [comment]
so i built this, just to make sure. 
It builds correctly. 
it installs the correct .sh in the ports sections. 
I installed Hero3 complete ED from GOG on my computer
i coped Data, Maps and Mp3 from the game on the computer to the vcmi folder in the ports folder on the PI

but there is a issue, it is now not starting. so i will need to take a look into whats going on. 
i hate when the devs change stuff on their end and it messes up my scripts

**Comment by Exarkuniv** [comment]
ok 
the script is now fixed and the game starts just fine for me
so youll need to update the scripts on your system so it get the latest versions

**Comment by EMiiiiiler** [comment]
OK cool I'll try it when I get home.
Do I need to git pull or call I just the retropie package manager to install?

I'm guessing it'll be a git pull

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Exarkuniv** [comment]
if you do this, just like when you first do the RetroPie-Extra install
``cd RetroPie-Extra/``
``./install-extras.sh``

there is a update option in the menu that will pull and replace the updated files

**Comment by EMiiiiiler** [comment]
@Exarkuniv I've updated it and tried re-running it but VCMI still isn't working. I'm re-doing a SSD with a fresh retropie so I can fully test this. It's the least I can do after all the amazing help you've given me

**Comment by EMiiiiiler** [comment]
Yep got Heroes 3 working on the fresh retropie install. I think using vcmibuilder created objects that shouldn't have been there. 
Do I need to configure the controller for Heroes 3? Can't move the cursor with my xbox controller

**Comment by Exarkuniv** [comment]
im glad that you got it working now.

sadly there is no nativlay controller support. you have to use a mouse and keyboard or use https://retropie.org.uk/docs/Universal-Controller-Calibration-%26-Mapping-Using-xboxdrv/ to map a keyboard to your controller.

there is another way to map a keyboard to a controller. im looking for it. ill post it when i find it

**Comment by EMiiiiiler** [comment]
amazing!! I'll try and use the guide you linked, if you find the other way let me know.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Exarkuniv** [comment]
if you need help with mapping the controller just ask on the [ forum ](https://retropie.org.uk/forum/).

I"m closing the ticket as the problem as been fixed
